import os

# 从环境变量中获取阿里云短信服务配置信息
ALIYUN_ACCESS_KEY_ID = os.getenv('ALIYUN_ACCESS_KEY_ID')
ALIYUN_ACCESS_KEY_SECRET = os.getenv('ALIYUN_ACCESS_KEY_SECRET')
ALIYUN_SIGN_NAME = os.getenv('ALIYUN_SIGN_NAME')
ALIYUN_REGISTER_TEMPLATE_CODE = os.getenv('ALIYUN_REGISTER_TEMPLATE_CODE')
ALIYUN_RESET_PASSWORD_TEMPLATE_CODE = os.getenv('ALIYUN_RESET_PASSWORD_TEMPLATE_CODE')